#!/bin/bash

current_hour=$(date +%H)

day_of_week=$(date +%A)

if [ $current_hour -ge 0 ] && [ $current_hour -lt 12 ]; then
   echo "Good Morning!"

elif [ $current_hour -ge 12 ]&&[ $current_hour -lt 18 ]; then
   echo "Good Afternoon!"

else
   echo "Good Evening!"
fi

if [ "$day_of_week" == "Friday" ]; then 
   echo "TGIF!"
fi


